services:
  # MSSQL Server
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1434:1433"
    container_name: mssql_container
    restart: always
    volumes:
      - mssql_data:/var/opt/mssql
volumes:
  mssql_data: