// <auto-generated />

using BlazorWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorWeb.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230612181014_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorWeb.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Category 1",
                            Price = 99.99m,
                            Title = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Category 2",
                            Price = 9.99m,
                            Title = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Category 3",
                            Price = 14.99m,
                            Title = "Product 3"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Category 4",
                            Price = 79.90m,
                            Title = "Product 4"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Category 5",
                            Price = 499.99m,
                            Title = "Product 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
